/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;


public class AboutUs extends javax.swing.JInternalFrame {

 
    public AboutUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelEma = new javax.swing.JLabel();
        jLabelEze = new javax.swing.JLabel();
        jLabelJon = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jButtonGitHub = new javax.swing.JButton();
        jButtonTrello = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("Sobre nosotros");

        jLabelEma.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelEma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEma.setText("Emanuel Schönfeld");
        jLabelEma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEmaMouseExited(evt);
            }
        });

        jLabelEze.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelEze.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEze.setText("Ezequiel Marrelli");
        jLabelEze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEzeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEzeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEzeMouseExited(evt);
            }
        });

        jLabelJon.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelJon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJon.setText("Jonatan Ballestero");
        jLabelJon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelJonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelJonMouseExited(evt);
            }
        });

        jbExit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
        jbExit.setText("Salir");
        jbExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jButtonGitHub.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonGitHub.setText("Repositorio");
        jButtonGitHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGitHubActionPerformed(evt);
            }
        });

        jButtonTrello.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonTrello.setText("Tablero de trabajo");
        jButtonTrello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrelloActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelEma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelEze, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelJon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonGitHub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonTrello, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(225, 225, 225))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEze, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonTrello)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonGitHub)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jbExit)
                        .addGap(306, 306, 306))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabelEma)
                .addGap(50, 50, 50)
                .addComponent(jLabelEze)
                .addGap(54, 54, 54)
                .addComponent(jLabelJon)
                .addGap(44, 44, 44)
                .addComponent(jButtonTrello)
                .addGap(30, 30, 30)
                .addComponent(jButtonGitHub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jbExit)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbExitActionPerformed

    private void jLabelJonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJonMouseClicked
     String link = "https://www.linkedin.com/in/jonballes/";
     addUrl(link);
    }//GEN-LAST:event_jLabelJonMouseClicked

    private void jLabelEmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmaMouseClicked
       String link = "https://www.linkedin.com/in/emanuel-schonfeld-691b67257/";
       addUrl(link);
    }//GEN-LAST:event_jLabelEmaMouseClicked

    private void jButtonTrelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrelloActionPerformed
       String link = "https://trello.com/b/8c3RGe3M/proyecto-arg-programa";
       addUrl(link);
    }//GEN-LAST:event_jButtonTrelloActionPerformed

    private void jButtonGitHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGitHubActionPerformed
        String link = "https://github.com/JonBalles/la25-ProyectoArgPrograma";
        addUrl(link);
    }//GEN-LAST:event_jButtonGitHubActionPerformed

    
    private void jLabelJonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJonMouseEntered
        jLabelJon.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabelJonMouseEntered

    private void jLabelJonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJonMouseExited
          jLabelJon.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelJonMouseExited

    
    private void jLabelEmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmaMouseEntered
        jLabelEma.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabelEmaMouseEntered

    private void jLabelEmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmaMouseExited
        jLabelEma.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelEmaMouseExited

    private void jLabelEzeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEzeMouseEntered
        jLabelEze.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabelEzeMouseEntered

    private void jLabelEzeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEzeMouseExited
        jLabelEze.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelEzeMouseExited

    private void jLabelEzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEzeMouseClicked
         String link = "https://www.linkedin.com/in/ezequiel-nicolas-marrelli-a67941292/";
        addUrl(link);
    }//GEN-LAST:event_jLabelEzeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGitHub;
    private javax.swing.JButton jButtonTrello;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEma;
    private javax.swing.JLabel jLabelEze;
    private javax.swing.JLabel jLabelJon;
    private javax.swing.JButton jbExit;
    // End of variables declaration//GEN-END:variables


private void addUrl(String url){
          try{
            if(Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI(url));
                }
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
}
}
